# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the workflow branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: kraag22/ansible
          path: ansible

      - name: Ansible version
        run: ansible --version

      - name: Run ansible
        uses: kraag22/action-ansible-playbook@v2.2.0
        with:
          playbook: site.yml
          directory: ./ansible/
          requirements: requirements.yml
          key: ${{secrets.PRIVATE_KEY}}
          inventory: |
            [ocean]
            ${{secrets.TARGET_IP}}    ansible_user=root
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --tags graphs
